<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
    <AssemblyName>PythonCoderGame</AssemblyName>
    <RootNamespace>PythonCoderGame</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\Music\*.mp3" />
    <Content Include="Assets\Music\*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>Music Resources\%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="INSTALLER\**\*.cs" />
    <EmbeddedResource Remove="INSTALLER\**\*" />
    <None Remove="INSTALLER\**\*" />
    <Content Remove="INSTALLER\**\*" />
  </ItemGroup>
</Project>
